# Generated by Django 3.2.16 on 2025-05-22 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, verbose_name='About-Heading')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default=None, upload_to='companyLogos/')),
                ('vision', models.TextField(default='')),
                ('company_name', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('founders', models.CharField(max_length=200)),
                ('founding_year', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('is_sotm', models.BooleanField(default=False)),
                ('facebook', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 5, 22, 20, 21, 53, 209818))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', models.TextField()),
                ('is_hero', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Opportunity Name')),
            ],
        ),
        migrations.CreateModel(
            name='Universal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_dp', models.ImageField(blank=True, default=None, null=True, upload_to='studentDp/')),
                ('facebook', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Opportunity Name')),
                ('register_url', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Link to register')),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotm.company')),
                ('tags', models.ManyToManyField(to='sotm.OpportunityTag')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
            },
        ),
    ]
