# Generated by Django 3.2.16 on 2025-06-12 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 17, 22, 23, 91071)),
        ),
    ]
