# Generated by Django 5.2.3 on 2025-06-13 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotm', '0002_alter_company_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 11, 52, 32, 406937)),
        ),
    ]
