# Generated by Django 3.2.16 on 2025-05-22 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.CharField(default='default.png', max_length=300)),
                ('has_completed', models.BooleanField(default=False)),
                ('college', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('completed_prog', models.BooleanField(default=False)),
                ('unique_code', models.CharField(default='d3ed5f8e', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('subtasks_completed', models.TextField(blank=True, default='')),
                ('facebook', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
                ('drive_link', models.CharField(default='Pending', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('icon_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibliity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Responsiblities',
            },
        ),
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(default='401975a13d', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('submission_url', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_ambassador.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskCompletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_allotted', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(default='497b2beb', max_length=8)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_ambassador.ambassador')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_ambassador.subtask')),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_ambassador.task'),
        ),
        migrations.CreateModel(
            name='CAPModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('unique_code', models.CharField(default='882e364d', max_length=8, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ambassador',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_ambassador.campaign'),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
