# Generated by Django 5.2.3 on 2025-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='unique_code',
            field=models.CharField(default='a09ac717', max_length=20),
        ),
        migrations.AlterField(
            model_name='capmoderator',
            name='unique_code',
            field=models.CharField(default='8b7e5b8b', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='secretkey',
            name='value',
            field=models.CharField(default='5da8d9e261', max_length=10),
        ),
        migrations.AlterField(
            model_name='subtaskcompletionrequest',
            name='unique_id',
            field=models.CharField(default='26d98904', max_length=8),
        ),
    ]
