# Generated by Django 5.2.3 on 2025-06-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0002_alter_ambassador_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassador',
            name='unique_code',
            field=models.CharField(default='5d4ba682', max_length=20),
        ),
        migrations.AlterField(
            model_name='capmoderator',
            name='unique_code',
            field=models.CharField(default='67df2d45', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='secretkey',
            name='value',
            field=models.CharField(default='252a8fb0af', max_length=10),
        ),
        migrations.AlterField(
            model_name='subtaskcompletionrequest',
            name='unique_id',
            field=models.CharField(default='3af6bfbc', max_length=8),
        ),
    ]
