# Generated by Django 3.2.16 on 2025-05-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('position', models.CharField(blank=True, default=None, max_length=100)),
                ('image', models.ImageField(blank=True, default=None, upload_to='memberImages/')),
                ('facebook', models.URLField(blank=True, default=None)),
                ('linkedin', models.URLField(blank=True, default=None)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('passing_out_date', models.DateField()),
            ],
        ),
    ]
