# Generated by Django 3.2.16 on 2025-05-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('about_event', models.TextField(max_length=1200)),
                ('image', models.ImageField(blank=True, default='', upload_to='events/')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('event', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.event')),
                ('prizes', models.TextField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_event', models.DateTimeField(blank=True, null=True)),
                ('details', models.CharField(max_length=300)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Timeline',
                'ordering': ('date_event',),
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, default='', upload_to='events/')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Event Images',
            },
        ),
    ]
