# Generated by Django 3.2.16 on 2025-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(upload_to='brochurePDF')),
            ],
        ),
        migrations.CreateModel(
            name='EsummitSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='EsponsorImage/')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('website', models.TextField(default='#')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_image', models.ImageField(default=None, upload_to='sponsorImage/')),
                ('sponsor_name', models.CharField(max_length=100)),
                ('sponsor_order', models.IntegerField(default=1)),
                ('sponsor_website', models.URLField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_description', models.TextField(max_length=1200)),
                ('event_order', models.IntegerField(default=1)),
                ('event_sponsors', models.ManyToManyField(to='sponsors.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Esummit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2023)),
                ('esummit_image', models.ImageField(blank=True, default=None, upload_to='esummitImage/')),
                ('esummit_sponsors', models.ManyToManyField(to='sponsors.EsummitSponsor')),
            ],
        ),
    ]
