# Generated by Django 3.2.16 on 2025-05-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('year_img', models.ImageField(blank=True, default=None, upload_to='esummitYear/')),
                ('year_desc', models.TextField(default='')),
                ('yt_link', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_img', models.ImageField(blank=True, default=None, upload_to='esummitSpeakers/')),
                ('speaker_title', models.CharField(default=None, max_length=500)),
                ('speaker_subtitle', models.TextField(default='')),
                ('speaker_desc', models.TextField(default='')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esummit.year_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Glimpse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glimpse_img', models.ImageField(blank=True, default=None, upload_to='esummitGlimpses/')),
                ('glimpse_desc', models.CharField(default=None, max_length=100)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esummit.year_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(blank=True, default=None, upload_to='esummitEvents/')),
                ('event_title', models.CharField(default=None, max_length=500)),
                ('event_detail', models.TextField(default='')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esummit.year_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(blank=True, default=None, upload_to='esummitSlider/')),
                ('title', models.CharField(default=None, max_length=500)),
                ('subtitle', models.TextField(default='')),
                ('btn_content', models.CharField(default=None, max_length=200)),
                ('btn_link', models.CharField(default=None, max_length=200)),
                ('is_hero', models.BooleanField(default=False)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esummit.year_detail')),
            ],
        ),
    ]
